<?

$MIME_TYPES = array(
	"image/pjpeg" => "jpg",
	"image/jpeg" => "jpg",
	"image/gif" => "gif",
	"image/png" => "png",
	"application/msword" => "doc",
	"application/macbinhex40" => "hqx",
	"application/octet-stream" => "exe",
	"application/x-msdownload" => "exe",
	"application/pdf" => "pdf",
	"application/postscript" => "ps",
	"application/smil" => "smi",
	"application/vnd.openxmlformats" => "docx",
	"application/x-director" => "dxr",
	"application/x-javascript" => "js",
	"application/x-shockwave-flash" => "swf",
	"application/x-stuffit" => "sit",
	"application/x-tar" => "tar",
	"application/zip" => "zip",
	"audio/mpeg" => "mp3",
	"audio/x-aiff" => "aif",
	"audio/x-realaudio" => "ra",
	"audio/x-wav" => "wav",
	"image/bmp" => "bmp",
	"image/gif" => "gif",
	"image/jpeg" => "jpg",
	"image/png" => "png",
	"image/tiff" => "tif",
	"model/vrml" => "vrml",
	"text/css" => "css",
	"text/html" => "htm",
	"text/plain" => "txt",
	"text/richtext" => "rtx",
	"text/rtf" => "rtf",
	"text/sgml" => "sgm",
	"text/tab-separated-values" => "tsv",
	"text/xml" => "xml",
	"video/mpeg" => "mpg",
	"video/quicktime" => "mov",
	"video/x-msvideo" => "avi",
);

?>