ALTER TABLE sm1_content_fileassoc DROP INDEX content_fileassoc__tableid;
ALTER TABLE sm1_content_fileassoc DROP INDEX content_fileassoc__table;
ALTER TABLE  `sm1_content_fileassoc` CHANGE  `content_fileassoc__table`  `content_fileassoc__table` VARCHAR( 128 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT  ''
ALTER TABLE  `sm1_content_fileassoc` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_extra` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_file2content_filecategory` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_filecategory` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_fileico` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_fileshowtype` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_fileshowtypeitem` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_hostallow` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_mailtemplate2content_user` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_mailtemplate` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_news2content_newsgroup` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_news` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_newsgroup` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_page` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_peeklist` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_peeklistitem` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_plugin` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_section2content_page` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_section` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_tags` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_template` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_text` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_user` ENGINE = MYISAM;
ALTER TABLE  `sm1_content_usergroup` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_changed` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_config` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_configadminview` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_configadminviewcolumn` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_deleted` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_relation` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_sitemanager` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_task` ENGINE = MYISAM;
ALTER TABLE  `sm1_core_translation` ENGINE = MYISAM;

DROP VIEW `sm1_content_user`;
DROP TABLE `sm1_content_user_extra`;
ALTER TABLE `sm1_content_user_base` RENAME `sm1_content_user`;
ALTER TABLE `sm1_content_user` DROP content_user__firstname;
ALTER TABLE `sm1_content_user` DROP content_user__lastname;
ALTER TABLE `sm1_content_user` DROP content_user__email;
ALTER TABLE `sm1_content_user` DROP content_user__hide_email;
ALTER TABLE `sm1_content_user` DROP content_user__phone;
ALTER TABLE `sm1_content_user` DROP content_user__company;
ALTER TABLE `sm1_content_user` DROP content_user__postcode;
ALTER TABLE `sm1_content_user` DROP content_user__city;
ALTER TABLE `sm1_content_user` DROP content_user__street;
ALTER TABLE `sm1_content_user` DROP content_user__country;
ALTER TABLE `sm1_content_user` DROP content_user__confirm_regulation;
ALTER TABLE `sm1_content_user` DROP content_user__confirm_userdata;
ALTER TABLE `sm1_content_user` DROP content_user__marketing;
ALTER TABLE `sm1_content_user` DROP content_user__comment;
ALTER TABLE `sm1_content_user` ADD content_user__security_token char(64) AFTER content_user__login_falsecount;
ALTER TABLE `sm1_content_user` ADD `content_user__security_token` char(64) AFTER `content_user__login_falsecount`;
ALTER TABLE `sm1_content_useracl` RENAME sm1_content_user2content_access;
ALTER TABLE `sm1_content_user2content_access` CHANGE `content_useracl__id` `sm_content_user2content_access` CHAR(36);
ALTER TABLE `sm1_content_user2content_access` CHANGE `content_useracl__bit` `content_user2content_access__bit` bigint(20);
ALTER TABLE `sm1_content_usergroupacl` RENAME `sm1_content_usergroup2content_access`;
ALTER TABLE `sm1_content_usergroup2content_access` CHANGE `content_usergroupacl__id` `sm_content_usergroup2content_access` CHAR(36);
ALTER TABLE `sm1_content_usergroup2content_access` CHANGE `content_usergroupacl__bit` `content_usergroup2content_access__bit` bigint(20);
ALTER TABLE `sm1_core_task` CHANGE `core_task___plugin` `core_task__plugin` varchar(255) NOT NULL;
ALTER TABLE `sm1_core_task` CHANGE `core_task___function` `core_task__function` varchar(255) NOT NULL;
ALTER TABLE `sm1_core_task` CHANGE `core_task___params` `core_task__params` text;
ALTER TABLE `sm1_core_task` CHANGE `core_task___status` `core_task__status` tinyint(4) DEFAULT NULL;
ALTER TABLE `sm1_core_task` CHANGE `core_task___result` `core_task__result` varchar(255) DEFAULT NULL;
ALTER TABLE `sm1_core_task` ADD `core_task__execution_time` float(11,2) AFTER `core_task__result`;
